### ISSUE TITLE
DateTime dependency may be skipped

### ISSUE THREAD

**Issue by bbrtj** [bk/Data-ULID#6]
This is dependency graph for Data::ULID:
![obraz](https://user-images.githubusercontent.com/44323413/200502880-a6939f39-4b76-4fa8-ac66-0ca5ef0e9feb.png)

DateTime dependency tree is huge, and it is only directly used in `ulid_date` function (not counting `isa` check in `_ulid`, as we don't use it there directly).

Would you accept a PR that remove DateTime dependency? How it would work is:
- during module compilation (in a `BEGIN` block) we try to load DateTime
- during `ulid_date` execution we check whether DateTime was loaded, and we throw exception if it wasn't (something like `"using ulid_date function requires DateTime module"`)
- in tests, we skip all the tests requiring DateTime if we don't have DateTime installed

**Comment by bk** [comment]
Wow, I hadn't realized DateTime was so heavy in terms of requirements. Your approach sounds like a really good idea. I'll take a look at your PR later this week - thank you!

**Comment by bbrtj** [comment]
@bk I allowed myself to do a development release to CPAN: https://metacpan.org/release/BRTASTIC/Data-ULID-1.1.3_01/view/lib/Data/ULID.pm (no need to have permissions assigned from the maintainer to do so)

This has all my recent commits from all the PRs merged. Should help you determine whether my changes are legitimate (with the help of CPAN testers)

**Comment by bk** [comment]
Thank you, very helpful :)

**Comment by bbrtj** [comment]
Seems like my development release still depends on DateTime, since I included old version of the module as well (for benchmarks). I'll remove it and do another release - the point is to see if it tests OK with and without DateTime on different versions.

**Comment by bk** [comment]
Thank you, @bbrtj - your three PRs are now merged.
